---
- hosts: borg
  gather_facts: true
  vars:
    # virtualenv_path may contain tilde in path (~/...) but this is used from the current user
    # on the ansible controller
    virtualenv_path: "{{ '/home/pi/.virtualenvs/borg' | expanduser }}"
    # path containing the borg binary
    borg_parent_path: "{{ '/'.join([virtualenv_path, 'bin'])}}"
  tasks:
    - include_vars: "vars/{{ ansible_os_family.lower() }}.yml"
    - import_tasks: tasks/setup.yml
    - import_tasks: tasks/init.yml
    - import_tasks: tasks/jobs.yml

