---
- hosts: borg
  vars:
    packages:
      - python3 
      - python3-dev 
      - python3-pip 
      - python-virtualenv 
      - libssl-dev 
      - openssl 
      - libacl1-dev 
      - libacl1 
      - build-essential
      - libfuse-dev 
      - fuse 
      - pkg-config
  tasks:
    - package:
        name: "{{ packages }}"
      become: true
    - pip:
        virtualenv: ~/.virtualenvs/borg 
        virtualenv_python: python3
        name: borgbackup

