---
- hosts: borg
  gather_facts: true
  vars:
    backup_jobs:
            - source: /media/data1/Gunnar/Documents
              archive: /media/data1/borgbackup
    # virtualenv_path may contain tilde in path (~/...) but this is used from the current user
    # on the ansible controller
    virtualenv_path: "{{ '/home/pi/.virtualenvs/borg' | expanduser }}"
    borg_path: "{{ '/'.join([virtualenv_path, 'bin/borg'])}}"
    packages:
      - python3 
      - python3-dev 
      - python3-pip 
      - python-virtualenv 
      - libssl-dev 
      - openssl 
      - libacl1-dev 
      - libacl1 
      - build-essential
      - libfuse-dev 
      - fuse 
      - pkg-config
  tasks:
    - name: Install debian specific package dependencies ...
      package:
        name: "{{ packages }}"
      become: true
    - pip:
        virtualenv: "{{ virtualenv_path | dirname }}"
        virtualenv_python: python3
        name: borgbackup
    - name: Deploy borgbackup wrapper script
      copy: 
        src: files/borgwrapper.sh
        dest: "{{ borg_path | dirname }}"
        mode: "u=rx"
    - name: Cronjob prepare environment
      cron:
        name: "{{ item.name }}"
        job: "{{ item.job }}"
        env: yes
      loop:
        - name: PATH
          job: "{{ '/'.join([virtualenv_path, 'bin']) }}:{{ ansible_env.PATH }}"
        - name: BORG_PASSPHRASE
          job: "{{ borg_passphrase }}"
    - name: Cronjob create job
      cron:
        name: Backup "{{ item.source }}"
        env: no
        job: "borgwrapper.sh {{ item.archive }} {{ inventory_hostname }}{{ item.source.replace('/', '-') }} {{ item.source }}"
        weekday: "*"
        minute: "29"
        hour: "11"
      loop:
        "{{backup_jobs }}"
